package com.gooduse.kitchenprep.ui

import androidx.compose.foundation.Image
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.rounded.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.gooduse.kitchenprep.*
import com.gooduse.kitchenprep.R

private val languages=listOf("English","Spanish","Portuguese","French","German","Italian","Dutch","Polish","Czech","Romanian","Hungarian","Swedish","Danish","Norwegian Bokmål","Finnish","Turkish","Arabic","Hebrew","Hindi","Bengali","Punjabi","Indonesian","Malay","Filipino","Vietnamese","Thai","Japanese","Korean","Simplified Chinese","Traditional Chinese","Russian")

@Composable fun Language(s:UiState,vm:KitchenPrepViewModel){var lo by remember{mutableStateOf(false)};var ro by remember{mutableStateOf(false)};Body(" ",false,{}){Text("Welcome",style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.SemiBold,modifier=Modifier.align(Alignment.CenterHorizontally));Text("Choose your language and region",modifier=Modifier.align(Alignment.CenterHorizontally));Box{OutlinedButton({lo=true},Modifier.fillMaxWidth().heightIn(min=48.dp)){Text(s.language,Modifier.weight(1f));Icon(Icons.Rounded.ExpandMore,null)};DropdownMenu(lo,{lo=false}){languages.forEach{DropdownMenuItem({Text(it)},{vm.setLanguage(it);lo=false})}}};Box{OutlinedButton({ro=true},Modifier.fillMaxWidth().heightIn(min=48.dp)){Text(s.region,Modifier.weight(1f));Icon(Icons.Rounded.ExpandMore,null)};DropdownMenu(ro,{ro=false}){listOf("United States (US)","Canada (CA)","United Kingdom (GB)","Australia (AU)","Other").forEach{DropdownMenuItem({Text(it)},{vm.setRegion(it);ro=false})}}};Primary("Continue",onClick=vm::localeNext);Image(painterResource(R.drawable.kitchen_prep_hero),null,Modifier.fillMaxWidth().height(210.dp),contentScale=ContentScale.Crop)}}

@Composable fun Privacy(s:UiState,vm:KitchenPrepViewModel){Body("Privacy & Ads",false,{}){Icon(Icons.Rounded.Shield,null,Modifier.size(50.dp).align(Alignment.CenterHorizontally),tint=Kpb.sageDark);Text("We keep your data on this device and never sell it.",modifier=Modifier.align(Alignment.CenterHorizontally));CardBox{Row(verticalAlignment=Alignment.CenterVertically){Icon(Icons.Rounded.PhoneAndroid,null);Spacer(Modifier.width(9.dp));Text("Local storage only")};Row(verticalAlignment=Alignment.CenterVertically){Icon(Icons.Rounded.PersonOff,null);Spacer(Modifier.width(9.dp));Text("No account required")};Row(verticalAlignment=Alignment.CenterVertically){Icon(Icons.Rounded.Campaign,null);Spacer(Modifier.width(9.dp));Text("Ads help keep the app free")}};CardBox{Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Icon(Icons.Rounded.SmartDisplay,null);Spacer(Modifier.width(9.dp));Text("Show ads",Modifier.weight(1f));Switch(s.adsEnabled,vm::setAds)};HorizontalDivider();Row(verticalAlignment=Alignment.CenterVertically){Icon(Icons.Rounded.Block,null);Spacer(Modifier.width(9.dp));Column{Text("Remove ads",fontWeight=FontWeight.Medium);Text("Monthly subscription",style=MaterialTheme.typography.bodySmall)}}};Primary("Continue",onClick=vm::privacyNext)}}

@Composable fun Home(s:UiState,vm:KitchenPrepViewModel){val b=s.board;Body("Kitchen Prep Board",false,{},bottom={Nav(0,vm)}){Text("Good morning, Chef.",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.SemiBold);Text("Let’s get everything ready.",color=Kpb.muted);CardBox{if(b!=null&&b.status in listOf(BoardStatus.ACTIVE,BoardStatus.PAUSED,BoardStatus.READY)){Text("Continue",style=MaterialTheme.typography.labelMedium,color=Kpb.muted);Text(b.title,fontWeight=FontWeight.SemiBold);Text("${b.tasks.size} items",style=MaterialTheme.typography.bodySmall);Primary("Resume Board",Icons.Rounded.PlayArrow){if(b.status==BoardStatus.READY)vm.startBoard()else vm.resume()}}else{Text("Start a prep board",fontWeight=FontWeight.SemiBold);Text("Keep what is now, next and waiting visible.");Primary("Create Board",Icons.Rounded.Add){vm.create()}}};val tasks=b?.tasks.orEmpty();Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){listOf("Now" to tasks.count{it.status==TaskStatus.ACTIVE},"Next" to tasks.count{it.status in listOf(TaskStatus.AVAILABLE,TaskStatus.BLOCKED)},"Waiting" to tasks.count{it.status==TaskStatus.WAITING},"Done" to tasks.count{it.status in listOf(TaskStatus.DONE,TaskStatus.SKIPPED)}).forEach{(k,v)->Surface(Modifier.weight(1f),shape=MaterialTheme.shapes.medium){Column(Modifier.padding(9.dp),horizontalAlignment=Alignment.CenterHorizontally){Text("$v",fontWeight=FontWeight.Bold);Text(k,style=MaterialTheme.typography.labelSmall)}}}};Text("Shortcuts",fontWeight=FontWeight.SemiBold);Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){OutlinedButton({vm.create()},Modifier.weight(1f).heightIn(min=54.dp)){Icon(Icons.Rounded.FactCheck,null);Spacer(Modifier.width(5.dp));Text("Quick Review")};OutlinedButton({vm.create()},Modifier.weight(1f).heightIn(min=54.dp)){Icon(Icons.Rounded.AddTask,null);Spacer(Modifier.width(5.dp));Text("New Board")}}}}

@Composable fun Create(s:UiState,vm:KitchenPrepViewModel){Body("Create Board",true,vm::back){OutlinedTextField(s.draftName,vm::setDraftName,label={Text("Board Name")},placeholder={Text("Weekend Dinner")},modifier=Modifier.fillMaxWidth());OutlinedTextField(s.draftNote,vm::setDraftNote,label={Text("Notes (optional)")},modifier=Modifier.fillMaxWidth(),minLines=3);OutlinedTextField(s.draftText,vm::setDraftText,label={Text("Prep items — one per line")},modifier=Modifier.fillMaxWidth(),minLines=5);CardBox{Text("Add from",fontWeight=FontWeight.SemiBold);Text("Manual entry, pasted text, Android Share text, an existing board or a template. Source text stays local.")};Primary("Create Board",enabled=s.draftName.isNotBlank()||s.draftText.isNotBlank(),onClick=vm::capture)}}

@Composable fun Review(s:UiState,vm:KitchenPrepViewModel){var x by remember{mutableStateOf("")};val t=s.board?.tasks.orEmpty();Body("Quick Review",true,vm::back){Text("Review parsed items before you continue.");if(t.isEmpty())Notice("No prep items yet. Add at least one task.",true);t.forEach{CardBox{Row(verticalAlignment=Alignment.CenterVertically){Icon(Icons.Rounded.WarningAmber,null,tint=Kpb.amber);Spacer(Modifier.width(9.dp));Column{Text(it.text,fontWeight=FontWeight.Medium);Text("${it.durationMin} min suggested",style=MaterialTheme.typography.bodySmall)}}}};Row(verticalAlignment=Alignment.CenterVertically){OutlinedTextField(x,{x=it},label={Text("Add item")},modifier=Modifier.weight(1f));IconButton({vm.addTask(x);x=""},Modifier.size(52.dp)){Icon(Icons.Rounded.AddCircle,null)}};CardBox{Text("Parsed Summary",fontWeight=FontWeight.SemiBold);Text("Items: ${t.size}")};Primary("Looks Good",enabled=t.isNotEmpty(),onClick=vm::reviewNext)}}
